car:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  rr_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_rr
    pid: {p: 100.0, i: 0.1, d: 10.0}

  rl_Wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_rl
    pid: {p: 100.0, i: 0.1, d: 10.0}

  fr_Wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_fr
    pid: {p: 100.0, i: 0.1, d: 10.0}

  fl_Wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_fl
    pid: {p: 100.0, i: 0.1, d: 10.0}

  # Position Controllers ---------------------------------------
  fr_Steer_controller:
    type: effort_controllers/JointPositionController
    joint: steer_fr
    pid: {p: 100.0, i: 0.1, d: 10.0}

  fl_Steer_controller:
    type: effort_controllers/JointPositionController
    joint: steer_fl
    pid: {p: 100.0, i: 0.1, d: 10.0}
